### ISSUE TITLE
need to update LD4P repo with current profiles

### ISSUE THREAD

**Issue by alexiskeely** [CECSpecialistI/UWLibCatProfiles#12]
@CECSpecialistI 

LD4P repo is out of date with current UW profiles. 

edit to add: this causes trouble during troubleshooting with Sinopia devs.

**Comment by briesenberg07** [comment]
Hello @alexiskeely and @gerontakos:

Sounds like action is needed.
I can certainly work on this first thing Thursday.
But I need more information.

If format-specific profiles have been edited post-output, outputting again with the same transforms won't be good, and in this case work will be needed on the transforms for format-specific profiles* to reflect those changes.

On the other hand, if the UW RDA profile has changed but format-specific profiles have not, outputting again should solve the problem*.

Which of the above applies? Or is the situation different? A combination of the two?

*RE: format-specific profile transforms, [changes made to mono transform] (https://github.com/CECSpecialistI/UWLibCatProfiles/commit/f9c883668676c1d29eccc0879a004fe5fee17c8c#r34721963) to deal with #11 should be made in the other format-specific transforms too.

**Comment by alexiskeely** [comment]
Hi @briesenberg07 ,

Very often you will see changes to format specific profiles for testing in Sinopia. Once the changes have been accepted, they are integrated into the master RDA. So in answer to your question, both apply.

**Comment by briesenberg07** [comment]
Thank you for clarifying @alexiskeely .
It sounds as if changes have been reflected in the RDA profile, so I will plan on outputting new format-specific profiles from this on Thursday morning.

**Comment by gerontakos** [comment]
Thank you! However there are some XSLT edits required after some changes to the RDA profile. For example, Crystal entered a new property "subtype" to the RDA profile; those will need to be written into the transforms so that the new property outputs. This is good -- we can deal with this! -- but I think we need a workflow, since we have division of labor. A document would do, or 2 docs: one doc to record changes made to the RDA profile that effect XSLT/format-specific-profile output, another doc that describes the whole process (to which we can refer when we forget how to do something in the workflow). Let's talk about this for a few minutes at our Thursday Sept 5 meeting.

**Comment by briesenberg07** [comment]
See #13 for one needed fix in RDA profile to output successful format-specific profiles.
Loadable mono profile pushed ( 005ad30663b70b9f4496268592b5a4863f4daf57 ) -- additional format profiles should be able to be output easily next week!
